include $(BUILDPATH)config.mk
include $(BUILDPATH)gccconfig.mk
include $(BUILDPATH)module.mk

compile:
	# Commands to compile and link your C-code
	# and to install them under the dist/ hierarchy

clean: luaclean
	# Commands to clean your compiled objects
