#!/bin/sh

exec 2>&1

# Initialize the I2C device
echo pcf8574 0x20 > /sys/bus/i2c/devices/i2c-0/new_device

BASE=`cat /sys/bus/i2c/devices/i2c-0/0-0020/gpio/gpiochip*/base`

# Export the lock pin
LOCKGPIO=$((BASE+7))
echo $LOCKGPIO > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio$LOCKGPIO/direction
echo 1 > /sys/class/gpio/gpio$LOCKGPIO/value

# Enable the RFID GPIO
# echo 252 > /sys/class/gpio/export
# echo out > /sys/class/gpio/gpio252/direction
# echo 0 > /sys/class/gpio/gpio252/value

stty -F /dev/ttyUSB0 0

if [ -r /tmp/root/mnt/doorcontrol.db ]; then
	DATABASE=/tmp/root/mnt/doorcontrol.db
else
	DATABASE=/mnt/doorcontrol.db
fi

exec doorcontrol -D ${DATABASE} -F /dev/ttyUSB0 \
    -L /sys/class/gpio/gpio$LOCKGPIO/value -p 12321
